# Image to build and test source code of user-service project.
FROM xxe_jdk7:latest

WORKDIR /home/gradle/service

COPY simpsons-xxe simpsons-xxe
COPY library_xml library_xml
ADD settings.gradle settings.gradle

USER root
RUN chown -R gradle:gradle .

USER gradle
CMD ["build", "--stacktrace"]
ENTRYPOINT ["gradle"]
