/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ua.in.smartjava;

import static org.junit.Assert.*;
import org.junit.Test;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
